In [10]:
import pandas as pd

cdng_data = pd.read_csv('./task_data/CDNG-KUST.csv', sep=';', header=None)

![Image alt](./imgs/img.png)

![Image alt](./imgs/img_1.png)

Типы объектов в названиях файлов и далее в API кодируются как "NGDU", "CDNG", "KUST", "WELL", "MEST", "OBJ", "PLAST".
Требуется реализовать, хранение, представление, навигацию и обработку данных структур.
2.	Требования к решению
1) Спроектировать и реализовать реляционное хранилище исходных данных
                - В том числе документировать его
2) Реализовать клиент-серверное приложения, которое должно:
	Предоставлять REST API в соответствии с приложением 1
	Предоставлять пользовательский WEB интерфейс позволяющий навигироваться и просматривать структуры целиком, связи, обрабатывать поисковые запросы (как минимум как в API) и т.д.
3) Документировать указанное решение
	Техническую документацию на решение описывающие архитектуру решения используемые технологии, решения в области безопасности и т.д.
	Документацию пользователя руководство пользователя, руководства по развертыванию и настройке, руководства по эксплуатации и т.д.
4) Подготовить и провести презентацию решения
	Презентация на 10-15 минут
Технические ограничения и дополнительные условия.
1)	Исходные файлы представлены в кодировке UTF-8.
2)	Разрешено использовать любые технологии и решения, но вся реализация должна выполняться на вычислительных мощностях в рамках предоставленного проекта VK Cloud.
3)	Предоставленные Nexus, GitLab желательно использовать с общими правилами и подходами  т.е. реджистри со всеми пакетами и образами в _, исходники и временные артефакты сборки в GitLab.
Результата должен быть представлен в виде работающего приложения развернутого и запущенного в предоставленном проекте _, в том числе реляционной СУБД, исходных текстов, скриптов, сценариев сборки и развертывания и т.д., презентационных материалов, документации и других сопутствующих материалов.
3.	Критерии оценки
Оценка решения производится по двум группам критериев:
1)	Автоматизированная оценка работоспособности REST API по критериям качество и скорость работы
2)	Ручные оценки, выставляемые членами экспертной комиссии по критериям:
	UX – качество, удобство и юзабельность интерфейса пользователя
	Sec – вопросы безопасности во всех этапах реализации решения от исходного кода до реализации и архитектуры развертывания
	Doc_Tech – техническая документация - документирование кода, маркдоун описания, документирование API, архитектуры, СУБД и т.д.
	Doc_User – эндюзерская документация, руководство пользователя, руководство по установке, руководство по настройке и т.д.
	DB – качество и структура реляционной базы данных
	Tech – оценка примененных технологий, как конечных так и технологий развёртывания DevOps и т.д.
	Pres – качество презентации решения. процесс представления решения целиком и ответы на вопросы

Все критерии одинаково важны и имеют примерно одинаковый вклад в общий результат.
4.	Рекомендации и ресурсы
Все решение целиком должно быть размещено в облаке _. При возникновении любых вопросов, в том числе по работе облака незамедлительно обращайтесь к организаторам в созданных чатах. Вопросы, которые кажутся вам актуальными для всех команд адресуйте в чат капитанов команд.
5.	Формат сдачи работы и сроки выполнения
_ команда должна сдать на проверку комиссии, путем сообщения в организованную группу в мессенджере:
1)	WORD документ содержащий:
	Координаты, логины и пароли UI интерфейса решения
	Координаты, логины и пароли реляционной СУБД
	Координаты, логины и пароли от всех иных компонент инфраструктуры (ОС, СУБД и т.д.)
2)	Структурированный zip без пароля, содержащий документацию и иные артефакты проекта.
3)	Исходные тексты и связанные артефакты в репозитории GitLab
4)	Образы и пакеты в Nexus
5)	На момент сдачи результата решение должно быть запущено на серверах. Решение должно предусматривать минимально достаточные процедуры самовосстановления работоспособности в случае сбоев и перезагрузки серверов.





Приложение 1
Спецификация REST API

1)	Endpoint сервисов задается в виде [base url]/сервис, где [base url] это [http://][адрес:порт][/путь]
2)	Все методы POST
3)	Необходимо реализовать 10 REST API сервисов:
	/object-exists
	/get-object-name
	/is-connected
	/find-connected
	/find-common-connected
	/find-exclusive-connected
	/count-all-connected
	/count-connected
	/find-by-sound-match
	/find-connected-by-sound-match

4)	Все параметры в запросах (см. таблицу 1) обязательные
5)	Все ответы всегда только с кодом 200 в случае корректного запроса или 400 в случае некорректных параметров запроса (некорректные ID, типа, параметров).
6)	Для 400 возвращается ответ с пустым телом.
7)	Описание методов приведено в таблице 1.

In [11]:
cdng_data.head(10)

        0         1         2         3
0  cdngid  cdngname    kustid  kustname
1       1    ЦДНГ-5  10998355    к.4756
2       1    ЦДНГ-5  10998338    к.5252
3       1    ЦДНГ-5  10998335    к.1164
4       1    ЦДНГ-5  10998324    к.5951
5       1    ЦДНГ-5  10998316    к.8650
6       1    ЦДНГ-5  10998315    к.7943
7       1    ЦДНГ-5  10998314    к.6887
8       1    ЦДНГ-5  10996351    к.4222
9       1    ЦДНГ-5  10993982     к.188

In [14]:
kust_well = pd.read_csv('./task_data/KUST-WELL.csv', sep=';', header=None)
kust_well.head(10)

          0         1        2        3
0    kustid  kustname    skvid  skvname
1  10998355    к.4756  1012678   56448Б
2  10998355    к.4756  1012439   50016К
3  10998355    к.4756  1012438    92480
4  10998355    к.4756  1012352    91294
5  10998355    к.4756  1012322   60435Б
6  10998355    к.4756  1012437   57132Б
7  10998355    к.4756  1012436     6892
8  10998338    к.5252  1012585   82449Б
9  10998338    к.5252  1012567     9052

In [15]:
mest_obj = pd.read_csv('./task_data/MEST-OBJ.csv', sep=';', header=None)
mest_obj.head(10)

        0                              1           2                        3
0  mestid                       mestname       objid                  objname
1     733                Дальне-Обильное   177918583                   ВТ79/9
2     733                Дальне-Обильное  1916485834                    ЯТ7/7
3     733                Дальне-Обильное  2036498630                    ЯТ5/7
4     733                Дальне-Обильное   840020939  Епт-альб-сеноманский ГЛ
5   -9521       Площадь Дальне-Нелымская  1976445698                      ЯТ5
6   -9605  Площадь Продольно-Нюрымская-2  1976445698                      ЯТ5
7     810              Продольно-Дневное    11626301                      ЕТX
8     810              Продольно-Дневное  1067878520                     ЕТ79
9   -9631            Площадь Иртышская 1  1976445698                      ЯТ5

In [16]:
ngdu_cdng = pd.read_csv('./task_data/NGDU-CDNG.csv', sep=';', header=None)
ngdu_cdng.head(10)

        0                1       2         3
0  ngduid         ngduname  cdngid  cdngname
1      12  НГДУ Соснанефть       1    ЦДНГ-5
2      12  НГДУ Соснанефть       2    ЦДНГ-3
3      12  НГДУ Соснанефть       4   ЦДНГ-12
4      12  НГДУ Соснанефть       5   ЦДНГ-11
5      12  НГДУ Соснанефть       6   ЦДНГ-10
6      12  НГДУ Соснанефть       7    ЦДНГ-9
7      12  НГДУ Соснанефть       8    ЦДНГ-8
8      12  НГДУ Соснанефть       9    ЦДНГ-7
9      12  НГДУ Соснанефть      10    ЦДНГ-6

In [17]:
ngdu_mest = pd.read_csv('./task_data/NGDU-MEST.csv', sep=';', header=None)
ngdu_mest.head(10)

        0                1       2                              3
0  ngduid         ngduname  mestid                       mestname
1      12  НГДУ Соснанефть     733                Дальне-Обильное
2      12  НГДУ Соснанефть   -9521       Площадь Дальне-Нелымская
3      12  НГДУ Соснанефть   -9605  Площадь Продольно-Нюрымская-2
4      12  НГДУ Соснанефть     810              Продольно-Дневное
5      12  НГДУ Соснанефть   -9631            Площадь Иртышская 1
6      12  НГДУ Соснанефть     706                        Вековое
7      12  НГДУ Соснанефть     790                Ближне-Обильное
8      12  НГДУ Соснанефть   -9996               Площадь Эпасская
9      12  НГДУ Соснанефть   -9982               Площадь Ютымская

In [18]:
obj_plast = pd.read_csv('./task_data/OBJ-PLAST.csv', sep=';', header=None)
obj_plast.head(10)

            0                        1        2          3
0       objid                  objname  plastid  plastname
1   177918583                   ВТ79/9     1834     ВТ79/9
2  1916485834                    ЯТ7/7     1788      ЯТ7/7
3  2036498630                    ЯТ5/7     1778      ЯТ5/7
4   840020939  Епт-альб-сеноманский ГЛ     1757         РЛ
5  1976445698                      ЯТ5     2176        ЯТ5
6    11626301                      ЕТX     2082      ЕТX/7
7  1067878520                     ЕТ79     2135       ЕТ79
8    11626301                      ЕТX     2083      ЕТX/5
9   231269484                    ВТ5+Y     2182      ВТ5+Y

In [19]:
plast_well = pd.read_csv('./task_data/PLAST-WELL.csv', sep=';', header=None)
plast_well.head(10)

         0          1        2        3
0  plastid  plastname    skvid  skvname
1     1834     ВТ79/9  1012678   56448Б
2     1834     ВТ79/9  1012439   50016К
3     1834     ВТ79/9  1012438    92480
4     1834     ВТ79/9  1012352    91294
5     1788      ЯТ7/7  1012322   60435Б
6     1778      ЯТ5/7  1012437   57132Б
7     1778      ЯТ5/7  1012436     6892
8     1778      ЯТ5/7  1012322   60435Б
9     1834     ВТ79/9  1012585   82449Б